backend:
  name: git-gateway
  branch: master
media_folder: public/assests/images
collections:
  - label: "Blog"
    name: "blog"
    folder: "posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
